/**
 * PSC Companion — Mock Data
 * Import: import { TEAM, INCIDENTS, ALERTS, HAZARD_ZONES, USER_PROFILE } from '../constants/mockData';
 */

/**
 * Current user profile — the person using the app.
 */
const NOW = Date.now()
const SECOND = 1000;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;

export const USER_PROFILE = {
  id: '0',
  name: 'You (FF Sallam)',
  role: 'Engine 7',
  status: 'onscene',
  level: 25,
  incidentId: 'INC-4821',
  division: 'Division Alpha',
  assignment: 'Search Team 1',
  coords: { latitude: 40.7138, longitude: -74.0060 },
  rank: 'Firefighter',
  station: 'Station 14 — Downtown',
  shift: 'Shift A · 0600–1800',
  hoursOnDuty: 8.5,
  certifications: [
    { name: 'Hazmat Ops', expires: '2026-09-15', active: true },
    { name: 'EMT-B', expires: '2026-03-01', active: true },
    { name: 'Rope Rescue Tech', expires: '2025-12-10', active: false },
    { name: 'Wildland FFT2', expires: '2027-01-20', active: true },
  ],
  gear: [
    { item: 'SCBA', status: 'checked', psi: '4200 PSI' },
    { item: 'Radio', status: 'active', channel: 'TAC-3' },
    { item: 'TIC', status: 'checked', note: 'Battery 88%' },
    { item: 'Irons', status: 'staged', note: 'On engine' },
  ],
};

export const TEAM = [
  {
    id: '1',
    name: 'Capt. Rivera',
    role: 'Incident Commander',
    status: 'onscene',
    lastUpdate: '2m ago',
    signal: 3,
    level: 47,
    incidentId: 'INC-4821',
    division: 'Command',
    assignment: 'Incident Command Post',
    coords: { latitude: 40.7142, longitude: -74.0064 },
  },
  {
    id: '2',
    name: 'Lt. Chen',
    role: 'Operations',
    status: 'safe',
    lastUpdate: '5m ago',
    signal: 4,
    level: 38,
    incidentId: 'INC-4819',
    division: 'Medical Group',
    assignment: 'Triage Lead',
    coords: { latitude: 40.7180, longitude: -74.0010 },
  },
  {
    id: '3',
    name: 'FF Torres',
    role: 'Engine 7',
    status: 'enroute',
    lastUpdate: '1m ago',
    signal: 2,
    level: 22,
    incidentId: 'INC-4821',
    division: 'Division Alpha',
    assignment: 'Search Team 1',
    coords: { latitude: 40.7125, longitude: -74.0045 },
  },
  {
    id: '4',
    name: 'PM Walsh',
    role: 'Medic 3',
    status: 'onscene',
    lastUpdate: '8m ago',
    signal: 4,
    level: 31,
    incidentId: 'INC-4821',
    division: 'Division Alpha',
    assignment: 'Medical Standby',
    coords: { latitude: 40.7135, longitude: -74.0058 },
  },
  {
    id: '5',
    name: 'FF Okafor',
    role: 'Ladder 2',
    status: 'needshelp',
    lastUpdate: '30s ago',
    signal: 1,
    level: 19,
    incidentId: 'INC-4821',
    division: 'Division Beta',
    assignment: 'Ventilation',
    coords: { latitude: 40.7145, longitude: -74.0068 },
  },
  {
    id: '6',
    name: 'Lt. Park',
    role: 'Hazmat',
    status: 'offline',
    lastUpdate: '12m ago',
    signal: 0,
    level: 35,
    incidentId: 'INC-4821',
    division: 'Division Beta',
    assignment: 'Perimeter Control',
    coords: { latitude: 40.7150, longitude: -74.0072 },
  },
  {
    id: '7',
    name: 'FF Martinez',
    role: 'Truck 7',
    status: 'needshelp',
    lastUpdate: '30s ago',
    signal: 1,
    level: 17,
    incidentId: 'INC-4821',
    division: 'Division Alpha',
    assignment: 'Interior Attack',
    coords: { latitude: 40.7140, longitude: -74.0062 },
  },
  {
    id: '8',
    name: 'Capt. Brooks',
    role: 'Engine 12',
    status: 'onscene',
    lastUpdate: '3m ago',
    signal: 3,
    level: 41,
    incidentId: 'INC-4815',
    division: 'Division Charlie',
    assignment: 'Exposure Protection',
    coords: { latitude: 40.7210, longitude: -74.0090 },
  },
  {
    id: '9',
    name: 'FF Kim',
    role: 'Engine 3',
    status: 'onscene',
    lastUpdate: '6m ago',
    signal: 2,
    level: 24,
    incidentId: 'INC-4815',
    division: 'Division Charlie',
    assignment: 'Water Supply',
    coords: { latitude: 40.7215, longitude: -74.0085 },
  },
  {
    id: '10',
    name: 'Lt. Vasquez',
    role: 'Rescue 1',
    status: 'enroute',
    lastUpdate: '1m ago',
    signal: 4,
    level: 33,
    incidentId: 'INC-4818',
    division: 'Rescue Group',
    assignment: 'Vehicle Extrication',
    coords: { latitude: 40.7090, longitude: -74.0030 },
  },
  {
    id: '11',
    name: 'FF Brooks',
    role: 'Medic 5',
    status: 'safe',
    lastUpdate: '9m ago',
    signal: 4,
    level: 28,
    incidentId: 'INC-4818',
    division: 'Medical Group',
    assignment: 'Patient Care',
    coords: { latitude: 40.7095, longitude: -74.0025 },
  },
  {
    id: '12',
    name: 'Capt. Walsh',
    role: 'Battalion 2',
    status: 'onscene',
    lastUpdate: '4m ago',
    signal: 3,
    level: 52,
    incidentId: 'INC-4818',
    division: 'Command',
    assignment: 'Sector Commander',
    coords: { latitude: 40.7085, longitude: -74.0035 },
  },
];

/**
 * Hazard zones — polygons/circles displayed as map overlays.
 */
export const HAZARD_ZONES = [
  {
    id: 'hz-1',
    label: 'Collapse Zone',
    type: 'danger',
    center: { latitude: 40.7142, longitude: -74.0064 },
    radius: 40, // meters
    incidentId: 'INC-4821',
  },
  {
    id: 'hz-2',
    label: 'Gas Leak Perimeter',
    type: 'warning',
    center: { latitude: 40.7146, longitude: -74.0070 },
    radius: 60,
    incidentId: 'INC-4821',
  },
  {
    id: 'hz-3',
    label: 'Crowd Area',
    type: 'caution',
    center: { latitude: 40.7180, longitude: -74.0010 },
    radius: 30,
    incidentId: 'INC-4819',
  },
];

export const INCIDENTS = [
  {
    id: 'INC-4821',
    type: 'Structure Fire',
    location: '742 Elm St',
    address: '742 Elm St, Unit B, Downtown District',
    priority: 'high',
    time: '14:23',
    units: 7,
    distance: '1.2 mi',
    hazards: ['Structural collapse risk', 'Possible gas leak'],
    assignedTeam: ['Capt. Rivera', 'PM Walsh', 'FF Okafor', 'FF Torres', 'FF Martinez'],
    resourcesRequested: ['Ladder truck', 'Hazmat unit', 'Additional medic'],
    callTranscript:
      'Caller reports heavy smoke from second floor of residential building. Occupants believed to still be inside. Caller states they heard an explosion before the fire started.',
    timeline: [
      { time: '14:23', event: 'Dispatch received — structure fire reported' },
      { time: '14:25', event: 'Engine 7 + Medic 3 dispatched' },
      { time: '14:28', event: 'Capt. Rivera on scene — confirms active fire' },
      { time: '14:31', event: 'FF Okafor requests assistance — Ladder 2' },
      { time: '14:33', event: 'Hazmat unit requested — possible gas leak' },
    ],
  },
  {
    id: 'INC-4819',
    type: 'Medical Response',
    location: 'Riverside Park',
    address: 'Riverside Park, North Entrance, Pavilion Area',
    priority: 'medium',
    time: '13:47',
    units: 2,
    distance: '0.8 mi',
    hazards: ['Crowd gathering'],
    assignedTeam: ['Lt. Chen', 'PM Walsh'],
    resourcesRequested: ['Additional medic'],
    callTranscript:
      'Caller reports adult male collapsed near the north pavilion. Conscious but disoriented. Possible heat exhaustion. Bystanders providing shade.',
    timeline: [
      { time: '13:47', event: 'Dispatch received — medical emergency' },
      { time: '13:50', event: 'Medic 3 dispatched' },
      { time: '13:55', event: 'Lt. Chen on scene — patient stable' },
    ],
  },
  {
    id: 'INC-4818',
    type: 'Vehicle Accident',
    location: 'Route 9 N / Exit 14',
    address: 'Route 9 North, Exit 14 Ramp, Westside Bridge Overpass',
    priority: 'high',
    time: '14:01',
    units: 3,
    distance: '2.1 mi',
    hazards: ['Fuel spill', 'Traffic hazard', 'Possible entrapment'],
    assignedTeam: ['Lt. Vasquez', 'FF Brooks', 'Capt. Walsh'],
    resourcesRequested: ['Heavy rescue', 'Hazmat — fuel spill'],
    callTranscript:
      'Caller reports a three-vehicle collision on the exit ramp. One vehicle overturned. Possible entrapment. Fuel visible on roadway. Multiple civilian bystanders present.',
    timeline: [
      { time: '14:01', event: 'Dispatch received — MVA with entrapment' },
      { time: '14:04', event: 'Rescue 1 + Medic 5 dispatched' },
      { time: '14:09', event: 'Lt. Vasquez on scene — confirms entrapment' },
      { time: '14:12', event: 'Hazmat requested — fuel spill confirmed' },
    ],
  },
  {
    id: 'INC-4815',
    type: 'Structure Fire',
    location: 'Maple Ave Industrial',
    address: '1180 Maple Ave, Industrial Lot C, North District',
    priority: 'high',
    time: '13:12',
    units: 5,
    distance: '3.4 mi',
    hazards: ['Chemical storage', 'Rapid fire spread'],
    assignedTeam: ['Capt. Brooks', 'FF Kim'],
    resourcesRequested: ['Second alarm companies', 'Hazmat team'],
    callTranscript:
      'Security guard reports smoke and flames from the storage building at the rear of the industrial lot. States chemical drums are stored in that section. No personnel inside.',
    timeline: [
      { time: '13:12', event: 'Dispatch received — industrial structure fire' },
      { time: '13:16', event: 'Engine 12 + Engine 3 dispatched' },
      { time: '13:22', event: 'Capt. Brooks on scene — second alarm struck' },
      { time: '13:28', event: 'Hazmat en route — chemical storage confirmed' },
      { time: '13:35', event: 'Fire contained to Building C' },
    ],
  },
];

export const ALERTS = [
  {
    id: '1',
    type: 'urgent',
    title: 'FF Okafor needs assistance',
    detail: 'Ladder 2 — last signal 30s ago',
    createdAt: NOW - 60000,
    status: 'active',
    requiresAction: true,
    linkedMemberId: '5',       
    linkedCoords: { latitude: 40.7142, longitude: -74.0064 }, 
  },
  {
    id: '2',
    type: 'urgent',
    title: 'FF Chen unresponsive',
    detail: 'Engine 5 — no movement detected for 2min',
    createdAt: NOW - 2 * MINUTE,
    status: 'active',
    requiresAction: true,
    linkedMemberId: '2',         
    linkedCoords: { latitude: 40.7180, longitude: -74.0010 },
  },
  {
    id: '3',
    type: 'urgent',
    title: 'Mayday declared — Engine 3',
    detail: 'Crew trapped on floor 4, structural collapse imminent',
    createdAt: NOW - 90000,
    status: 'acknowledged',
    requiresAction: true,
  },
  {
    id: '4',
    type: 'warning',
    title: 'Capt. Rivera needs backup',
    detail: 'High-angle rescue required. Original team overwhelmed by terrain',
    createdAt: NOW - 5 * MINUTE,
    status: 'active',
    requiresAction: false,
  },
  {
    id: '5',
    type: 'warning',
    title: 'Wind shift detected',
    detail: 'Fire behavior change expected — reassess escape routes',
    createdAt: NOW - 8 * MINUTE,
    status: 'active',
    requiresAction: false,
  },
  {
    id: '6',
    type: 'warning',
    title: 'Accountability check overdue',
    detail: 'PAR not received from Division B in 10min',
    createdAt: NOW - 12 * MINUTE,
    status: 'acknowledged',
    requiresAction: false,
  },
  {
    id: '7',
    type: 'info',
    title: 'Location accuracy degraded',
    detail: 'GPS signal weak indoor',
    createdAt: NOW - MINUTE,
    status: 'active',
    requiresAction: false,
  },
  {
    id: '8',
    type: 'info',
    title: 'Staging area updated',
    detail: 'Command moved to north parking lot',
    createdAt: NOW - 15 * MINUTE,
    status: 'active',
    requiresAction: false,
  },
  {
    id: '9',
    type: 'urgent',
    title: 'FF Martinez PASS alarm',
    detail: 'Truck 7 — PASS device activated, floor 2',
    createdAt: NOW - 30 * MINUTE,
    status: 'resolved',
    requiresAction: false,
  },
  {
    id: '10',
    type: 'warning',
    title: 'Air supply low — FF Brooks',
    detail: 'SCBA at 25% — exit initiated',
    createdAt: NOW - 45 * MINUTE,
    status: 'resolved',
    requiresAction: false,
  },
  {
    id: '11',
    type: 'info',
    title: 'Battery critical warning',
    detail: 'Low battery 15% — charge device',
    createdAt: NOW - 5 * HOUR,
    status: 'active',
    requiresAction: false,
    resolveKey: 'battery_low', 
  },
];
